version: "3.8"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    container_name: kdalytics-elasticsearch
    environment:
      - node.name=kdalytics-es01
      - cluster.name=kdalytics-es-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - kdalytics-network

  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.0
    container_name: kdalytics-kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - kdalytics-network

volumes:
  elasticsearch-data:
    driver: local

networks:
  kdalytics-network:
    driver: bridge
